using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forja.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AnalyticsEntitiesPropertyChanges : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:PostgresExtension:hstore", ",,");

            migrationBuilder.Sql(
                @"ALTER TABLE analytics.""AuditLogs"" 
                ALTER COLUMN ""Details"" TYPE hstore 
                USING ""Details""::hstore;"
            );

            migrationBuilder.Sql(
                @"ALTER TABLE analytics.""AnalyticsSessions"" 
                ALTER COLUMN ""Metadata"" TYPE hstore 
                USING ""Metadata""::hstore;"
            );

            migrationBuilder.Sql(
                @"ALTER TABLE analytics.""AnalyticsEvents"" 
                ALTER COLUMN ""Metadata"" TYPE hstore 
                USING ""Metadata""::hstore;"
            );

            migrationBuilder.Sql(
                @"ALTER TABLE analytics.""AnalyticsAggregates"" 
                ALTER COLUMN ""Id"" DROP IDENTITY;"
            );

            migrationBuilder.Sql(
                @"ALTER TABLE analytics.""AnalyticsAggregates"" 
                ALTER COLUMN ""Id"" TYPE uuid USING gen_random_uuid();"
            );
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .OldAnnotation("Npgsql:PostgresExtension:hstore", ",,");

            migrationBuilder.Sql(
                @"ALTER TABLE analytics.""AuditLogs"" 
                ALTER COLUMN ""Details"" TYPE text 
                USING ""Details""::text;"
            );

            migrationBuilder.Sql(
                @"ALTER TABLE analytics.""AnalyticsSessions"" 
                ALTER COLUMN ""Metadata"" TYPE text 
                USING ""Metadata""::text;"
            );

            migrationBuilder.Sql(
                @"ALTER TABLE analytics.""AnalyticsEvents"" 
                ALTER COLUMN ""Metadata"" TYPE text 
                USING ""Metadata""::text;"
            );

            migrationBuilder.Sql(
                @"ALTER TABLE analytics.""AnalyticsAggregates"" 
                ALTER COLUMN ""Id"" TYPE integer 
                USING ""Id""::integer;"
            );

            migrationBuilder.Sql(
                @"ALTER TABLE analytics.""AnalyticsAggregates"" 
                ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;"
            );
        }
    }
}
